### ISSUE TITLE
getGlobal returns basic object rather than class instance.

### ISSUE THREAD

**Issue by envygeeks** [electron/spectron#70] opened 2016-06-23 13:56 UTC
When we create our browser window we also initialize a Configuration object which is stored in the global and gotten again via `getGlobal` so that we don't have to constantly initialize.  In Electron this works out great because we can do `global.appConfig = new Config(app)` and then pull it out with getGlobal later and store it for the entire browser to have access to.

However, spectron only returns the values that are initialized upon class creation and none of the getters, setters or other methods that are defined on the class.  A basic example:

```js
class Hello {
  constructor() {
    this.valueOne = "works"
    this.valueTwo = "works"
  }

  get world() {
    return "DoesntWork"
  }
}

global.appConfig = new Hello()
```

```js
import { Application } from "spectron"
import { assert } from "chai"

describe("hello.js", function() {
  before(function() {
    this.app = new Application({
      path: "./node_modules/.bin/electron",
      chromeDriverLogPath: "./chrome.driver.log",
      args: ["./app/entry.js"]
    })

    return this.app.start(
      //
    )
  })

  after(function() {
    if (this.app && this.app.isRunning()) {
      this.app.stop(
        //
      )
    }
  })

  describe("#world", function() {
    it("should be a function", async function() {
      let config = await this.app.electron.remote.getGlobal("appConfig")
      assert.isFunction(config.world)
    })
  })
})
```

This ultimately fails because world is not even defined for some reason when `getGlobal` gets it, however... `valueOne` and `valueTwo` are there and ready to be tested/used.

**Comment by envygeeks** [comment] 2016-06-23 14:50
This seems to even happen when trying to get the global via 
```js
let config = await this.app.client.execute(() => { return app.config })
```

**Comment by kevinsawicki** [comment] 2016-06-23 15:56
Hmm, yeah, I wonder if it is because of the `get world() {` syntax and somewhere it is not being handled when serializing/deserializing to JSON.

Will take a look.

**Comment by kevinsawicki** [comment] 2016-07-05 16:29
> This seems to even happen when trying to get the global via

Yeah, it looks like calling `JSON.stringify` on this object doesn't include the ES6 style getters on the class. The ChromeDriver protocol which spectron builds on top of only supports receiving JSON responses.

I can reproduce this directly from Electron if you run `JSON.stringify(require('electron').remote.getGlobal('appConfig'))` from the Console tab of the dev tools.

If you want to verify those getter style properties you'll need to access them directly in the execute callback.

```js
let world = await this.app.client.execute(() => { return require('electron').getGlobal('appConfig').world })
```

Closing this out.

**Closed by kevinsawicki** 2016-07-05 16:29 UTC

**Comment by envygeeks** [comment] 2016-07-05 19:48
@kevinsawicki is there no better way than that? Some of our methods (getters included) will return a promise and promises in promises via spectron and mocha with chai (or even without) don't work out too well because errors do not surface properly through execute.  And even half the time we ask for the promise directly through execute it still doesn't work right.

**Comment by kevinsawicki** [comment] 2016-07-05 20:06
> is there no better way than that?

You might want to use a testing library where your specs run directly inside the app's window instead of driving them externally and being restricted to JSON communication.

It sounds like you are doing something closer to unit testing which spectron isn't designed for. It is meant to simulate the user's interaction with the app, clicking, moving, scrolling, etc. So for example, instead of waiting on a promise via spectron, you wait for for UI element to change state based on entering text, clicking buttons, etc.

> Some of our methods (getters included) will return a promise and promises in promises via spectron and mocha with chai (or even without) don't work out too well because errors do not surface properly through execute.

Can you provide a minimal example of this? Would be happy to look into it.

**Comment by envygeeks** [comment] 2016-07-06 03:33
@kevinsawicki well... I actually kinda assumed that a few days ago and you just confirmed it and we moved to a mixture of electron-mocha and spectron to do exactly what you just stated and it works out great.
