### ISSUE TITLE
app.webContents.getURL() hangs forever after navigation

### ISSUE THREAD

**Issue by salomvary** [electron/spectron#139] opened 2016-11-01 21:14 UTC
Given this app:

index.html:
```html
<a href="http://example.com">go to example.com</a>
```

main.js:
```js
const {app, BrowserWindow} = require('electron')
var win
app.on('ready', () => {
  win = new BrowserWindow({width: 800, height: 600})
    .loadURL(`file://${__dirname}/index.html`)
})
```

and `test.js`:

```js
'use strict'

const { Application } = require('spectron')

const app = new Application({
  args: [ 'main.js' ],
  path: 'node_modules/.bin/electron'
})

app.start()
  .then(() => app.client.waitUntilWindowLoaded())
  .then(() => app.webContents.getURL())
  .then(url => console.log(url))
  .then(() => app.client.click('=go to example.com'))
  .then(() => app.webContents.getURL())
  .then(url => console.log(url))
```

When running `node test.js`:
 
Expected: application loads example.com and logs 'http://example.com'.

Actual: application does not navigate and does not log.

If the last two lines are removed from `test.js`, the navigating to example.com works as expected.

Electron v1.4.4
Spectron 3.4.0
Node 6.2.2

**Comment by MarshallOfSound** [comment] 2016-11-01 21:23
Although poorly named.  This is a duplicate of #64 

Any navigation inside 'Electron' recreated the wevContents which causes a few issues.  I was working in a fix for this a while ago but it is quite complicated.

**Closed by MarshallOfSound** 2016-11-01 21:23 UTC
